echo "##Start" > 1-Generics.md
echo "##Start" > 2-Collections-before-generics.md
echo "##Start" > 3-Using-Generics.md
echo "##Start" > 4-Generic-Collections.md
echo "##Start" > 5-Generic-Parameters.md
echo "##Start" > 6-Generic-Constraints.md
echo "##Start" > 7-Generic-Methods.md
echo "##Start" > 8-Generic-Interfaces.md
echo "##Start" > 9-Generic-Delegates.md
echo "##Start" > 10-Variance.md